server:
  port: 9998
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com.lra.**.entity
# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.101.128.83:3306/my_shop
    username: liangruian
    password: 123456
  profiles:
    active: common
  redis:
    database: 0
    host: 47.101.128.83
    port: 6379
    password:
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: 1000
user:
  registerString: user_register_code_
  codeTimeout: 300
logging:
  file:
    name: app.log
